# Generated by Django 3.1.2 on 2020-10-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
